#!/usr/bin/python3 

from instagrapi import Client 
from argparse import ArgumentParser
import os, config 
from urllib import request 
from string import ascii_lowercase 
from random import choice 
import re 

cl = Client() 

def rand_gen():

    letters = ascii_lowercase
    name = ""

    for i in range(10):
        name += choice(letters)

    return name

def get_video(url,dest,prefix=""): 
    
    print("[kaizoku] Downloading video..") 

    if prefix:
        file_name = prefix + ".mp4"
    else:
        file_name = rand_gen() + ".mp4" 

    if dest:
        file_name = os.path.join(dest,file_name) 

    request.urlretrieve(url,file_name) 

def get_img(url,dest,prefix=""):

    print("[kaizoku] Downloading image..") 

    if prefix:
        file_name = prefix + ".jpg"
    else:
        file_name = rand_gen() + ".jpg" 

    if dest:
        file_name = os.path.join(dest,file_name) 

    request.urlretrieve(url,file_name) 


def parse():

    parser = ArgumentParser() 
    parser.add_argument('url',type=str,help="url of media",nargs='*') 
    parser.add_argument('-ga','--get-all-stories', type=str, help="usernames from which to download all stories",nargs="*") 
    parser.add_argument('-s','--saved', type=int,help='the number of posts to fetch from saved messages (0 would fetch all)') 
    parser.add_argument('-d','--destination', type=str,help="the directory in which to save downloaded files",nargs="?") 
    parser.add_argument('--cookies-from-browser', type=str,help="name of the browser from which to import cookies") 
    
    arguments = parser.parse_args() 
    return arguments

def get_story(arr):
    
    try: 
        info = cl.story_info(arr[-1]) 
        return info
    
    except: 

        info = {}
        userinfo = cl.user_info_by_username(arr[-2]) 
        story_info = cl.user_stories(userinfo.pk) 

        for story in story_info:
            id_arr = story.id.split('_') 

            if id_arr[0] == arr[-1]: 
                return story


args = parse() 
session_id = "" 

if args.cookies_from_browser: 
    session_id = config.get_cookies(args.cookies_from_browser) 

else:
    session_id = config.parse_conf()
cl.login_by_sessionid(session_id) 


if args.url: 
    
    media_dict = {} 
    for url in args.url:
        story = re.search("^https?://www.instagram.com/stories*",url) 

        if story: 
            story_arr = url.rstrip('/') 
            story_arr = story_arr.split('/') 
            
            info = get_story(story_arr)

            if info.video_url: 
                get_video(info.video_url,args.destination) 

            elif info.thumbnail_url: 
                get_img(info.thumbnail_url,args.destination)

        else:
            media_id = cl.media_pk_from_url(url) 
            media_dict = cl.media_info(media_id).dict()

        if media_dict: 

            if media_dict['media_type'] == 2: 
                get_video(media_dict['video_url'],args.destination) 

            if media_dict['media_type'] == 1: 
                get_img(media_dict['thumbnail_url'],args.destination) 

            if media_dict['media_type'] == 8: 

                for element in media_dict['resources']: 
                    if element['media_type'] == 1: 
                        get_img(element['thumbnail_url'],args.destination)

                    if element['media_type'] == 2: 
                        get_video(element['video_url'],args.destination) 

if args.get_all_stories:

    for user in args.get_all_stories:

        userinfo = cl.user_info_by_username(user) 
        story_info = cl.user_stories(userinfo.pk) 

        story_no = 1
        for story in story_info: 
            if story.video_url: 
                prefix = user + "_story_" + str(story_no) 
                get_video(story.video_url,args.destination,prefix) 
                story_no += 1

            elif story.thumbnail_url: 
                prefix = user + "_story_" + str(story_no) 
                get_img(story.thumbnail_url,args.destination,prefix)
                story_no += 1

if args.saved:

    collections = cl.collection_medias('ALL_MEDIA_AUTO_COLLECTION',amount=args.saved) 
    col_no = 1

    for collection in collections:
        if collection.media_type == 2: 
            prefix = "collection_" + str(col_no)
            get_video(collection.video_url,args.destination,prefix) 
            col_no += 1

        if collection.media_type == 1: 
            prefix = "collection_" + str(col_no)
            get_img(collection.thumbnail_url,args.destination,prefix) 
            col_no += 1

        if collection.media_type == 8: 
            album_no = 1
            for element in collection.resources: 
                if element.media_type == 1: 
                    prefix = "collection_" + str(col_no) + "_" + str(album_no)
                    get_img(element.thumbnail_url,args.destination,prefix)
                    album_no += 1

                if element.media_type == 2: 
                    prefix = "collection_" + str(col_no) + "_" + str(album_no)
                    get_video(element.video_url,args.destination,prefix) 
                    album_no += 1

            col_no += 1

